"""Deterministic, local procedural SFX post-production; never changes video/source."""
import json,pathlib,hashlib,wave,collections,math
import numpy as np
P=pathlib.Path(__file__).resolve().parent; SR=48000; DURATION=15722/30
X=json.loads((P/'semantic-timeline.json').read_text()); parts={p['id']:p for p in X['parts']}
A=P/'assets';A.mkdir(exist_ok=True)
def save(f,a):
 with wave.open(str(f),'wb') as w:w.setnchannels(1 if a.ndim==1 else a.shape[1]);w.setsampwidth(2);w.setframerate(SR);w.writeframes(np.round(np.clip(a,-1,1)*32767).astype('<i2').tobytes())
def noise(n,rng,low,high):
 z=rng.normal(0,1,n);f=np.fft.rfftfreq(n,1/SR);H=(1-np.exp(-(f/low)**2))*np.exp(-(f/high)**4);v=np.fft.irfft(np.fft.rfft(z)*H,n);return v/(np.std(v)+1e-12)
assets={}
for idx,(name,dur,kind) in enumerate([('wood-contact',.18,'wood'),('dowel-seat',.10,'wood'),('metal-seat',.14,'metal'),('driver-soft',.60,'driver'),('cam-turn',.26,'driver'),('mechanism-movement',3.,'movement'),('hinge-movement',1.9,'movement'),('soft-confirmation',.18,'wood')]):
 n=round(dur*SR);t=np.arange(n)/SR;rng=np.random.default_rng(311613+idx)
 if kind in ['wood','metal']:
  decay=.030 if name=='dowel-seat' else .050 if kind=='wood' else .035
  freqs=[210,430,790,1270] if kind=='wood' else [720,1380,2490,3670]
  sig=noise(n,rng,100,3500 if kind=='wood' else 5000)*np.exp(-t/(decay*.42))*.40
  for k,f in enumerate(freqs):sig+=np.sin(2*np.pi*f*t+rng.uniform(-.4,.4))*np.exp(-t/(decay/(1+k*.16)))*(.23/(1+k))
 else:
  sig=noise(n,rng,120,1900 if kind=='driver' else 1300)*(.6+.18*np.sin(2*np.pi*(13 if kind=='driver' else 3.7)*t))
  sig+=noise(n,rng,800,3800)*.07
  if kind=='driver':sig*=.65+.35*np.maximum(0,np.sin(2*np.pi*24*t))**2
 # No synthesized music, beep, boom, whoosh, narration or recorded external asset.
 fade=min(.015,dur/5);env=np.minimum(1,t/fade)*np.minimum(1,np.maximum(0,(dur-t)/(.055 if kind=='movement' else .025)))
 sig*=env;sig=sig/(np.max(np.abs(sig))+1e-12)*.58;save(A/(name+'.wav'),sig)
 assets[name]={'file':'assets/'+name+'.wav','samples':len(sig),'duration':dur,'sampleRate':SR,'channels':1,'source':'Locally generated by build-audio.py; deterministic band-limited noise and damped resonances','license':'Original procedural output; no third-party audio or sample license involved. No claim about exclusive copyright.','attributionRequired':False,'modificationStatus':'Generated locally; fades, amplitude shaping, gain and duration adapted during mix','seed':311613+idx,'sha256':hashlib.sha256((A/(name+'.wav')).read_bytes()).hexdigest()}
(P/'asset-provenance.json').write_text(json.dumps({'externalAssets':[],'musicDecision':'MUSIC_ASSET_REQUIRED','musicUsed':False,'assets':list(assets.values())},indent=2))
candidates=[];skipped=[]
def cue(st,sh,a,index,start,event,asset,onset,dur,basis,window,contact=False,gain=-14):
 eventtime=onset
 if contact:onset=math.ceil(onset*30-1e-8)/30;window=[onset,onset];basis+=' Contact is aligned to the first master frame showing the completed seat (never the preceding frame).'
 candidates.append({'semanticEventTimestamp':eventtime,'cueId':f'C{len(candidates)+1:04d}','globalTimestamp':onset,'semanticEvent':event,'step':st,'sceneId':sh.get('sceneId'),'shotId':sh['id'],'actionIndex':index,'operationId':a.get('id',f'{sh["id"]}:action-{index}'),'relatedPart':a.get('target'),'relatedHardware':parts.get(a.get('target'),{}).get('name'),'connection':a.get('connection') or a.get('anchorB'),'soundAsset':assets[asset]['file'],'gainDb':gain,'duration':dur,'fadeIn':min(.012,dur*.15),'fadeOut':min(.045,dur*.25),'rationale':basis,'syncBasis':{'actionType':a['type'],'actionStart':start,'actionDuration':a.get('duration',0),'permittedWindow':window,'contactEvent':contact},'action':a})
def derive(st,sh,a,i,shotstart):
 typ=a['type'];d=a.get('duration',0);start=shotstart+a.get('at',0);end=start+d;target=a.get('target','');part=parts.get(target,{});name=part.get('name','').lower()
 if d<=0:return
 if typ.startswith('install') and typ!='installWasher':
  if typ in ['installScrew','installBolt','installNut'] and a.get('installation',{}).get('mechanicalPhases') and not('cam' in target.lower() or 'cam' in name):
   w=a['installation'].get('motionTiming',{'approach':.35,'contact':.1,'feed':.5,'seat':.05});total=sum(w.values());feed=start+d*(w['approach']+w['contact'])/total;feedend=feed+d*w['feed']/total
   event='SCREW_TIGHTEN' if typ=='installScrew' else 'BOLT_TIGHTEN' if typ=='installBolt' else 'NUT_TIGHTEN'
   if st in [30,31] and 'H23' in target:event='WALL_ANCHOR'
   length=min(.42 if st in [25,26,27,30,31] else .30,feedend-feed);on=feed+(feedend-feed-length)*.35
   cue(st,sh,a,i,start,event,'driver-soft',on,length,'Restrained driver friction inside actual screw-feed/spin phase after approach/contact; representative fastener only.',[feed,feedend],gain=-16)
  else:
   ev='DOWEL_INSERT' if typ=='installDowel' else 'CAM_INSERT' if 'cam' in target.lower() or 'cam' in name else 'BRACKET_PLACE' if 'bracket' in name or 'H15' in target or 'H20' in target or target in ['E5','D8','D9','E1--1','E1-1'] or typ=='installBracket' else 'BEARING_SEAT' if 'H19' in target else 'PISTON_ATTACH' if target.startswith('E2') else 'PART_SEAT'
   asset='dowel-seat' if ev=='DOWEL_INSERT' else 'metal-seat' if ev in ['CAM_INSERT','BRACKET_PLACE','BEARING_SEAT','PISTON_ATTACH'] else 'wood-contact'
   cue(st,sh,a,i,start,ev,asset,end,assets[asset]['duration'],'Contact onset at exact completed seating endpoint; no approach/staging impact.',[end,end],contact=True)
 elif typ=='rotate' and sh.get('type')=='TIGHTEN_HARDWARE':
  ev='CAM_TURN' if 'cam' in target.lower() else 'BOLT_TIGHTEN';asset='cam-turn' if ev=='CAM_TURN' else 'driver-soft';length=min(d*.85,.24)
  cue(st,sh,a,i,start,ev,asset,start+d*.08,length,'Actual tightening rotation on already inserted hardware; SFX stays inside rotation.',[start,end],gain=-15)
 elif typ=='telescopicLink' and a.get('anchorB') and st in [26,27]:cue(st,sh,a,i,start,'PISTON_ATTACH','metal-seat',end,.14,'Eye reaches its real anchored endpoint only at action completion.',[end,end],contact=True,gain=-13)
 elif typ=='pivotPose':
  if st==25 and sh['id']=='S25-route-6':cue(st,sh,a,i,start,'BEARING_SEAT','metal-seat',end,.14,'Both bearings finish descending into the cradle; no sound on the supported approach.',[end,end],contact=True,gain=-12)
  elif target=='bed-motion-root' and ('close' in sh['id'] or 'open' in sh['id'] or st==27):
   ev='BED_CLOSE' if 'close' in sh['id'] else 'BED_OPEN' if 'open' in sh['id'] else 'MECHANISM_MOVEMENT'
   cue(st,sh,a,i,start,ev,'mechanism-movement',start+.04,max(.1,d-.08),'Soft continuous friction only within actual articulated movement; no impact while airborne.',[start,end],gain=-22)
   if ev=='BED_CLOSE':cue(st,sh,a,i,start,'PART_SEAT','wood-contact',end,.18,'Closed endpoint soft seated contact follows completed bed motion.',[end,end],contact=True,gain=-17)
  elif target.startswith('leg-') and ('fold' in sh['id'] or 'deploy' in sh['id']):
   cue(st,sh,a,i,start,'LEG_MOVEMENT','hinge-movement',start+.04,d-.08,'Soft hinge friction synchronized with folding/deploying; mirrored simultaneous legs represented once.',[start,end],gain=-23)
   cue(st,sh,a,i,start,'MECHANISM_CLICK','metal-seat',end,.14,'Light end-of-travel leg click at completed pose, never before contact.',[end,end],contact=True,gain=-19)
 elif typ=='move' and st==29 and sh.get('type')=='INSERT_PART' and target.startswith('leg-'):cue(st,sh,a,i,start,'LEG_ATTACH','metal-seat',end,.14,'Leg reaches the carrier joint after its final seating move.',[end,end],contact=True,gain=-14)
for st in X['directorPlan']['steps']:
 cursor=next(s['start'] for s in X['scenes'] if s['id']==st['id'])
 for sh in st['shots']:
  for i,a in enumerate(sh['actions']):derive(st['step'],{**sh,'sceneId':st['id']},a,i,cursor)
  cursor+=sh['duration']
for s in X['scenes']:
 if s.get('phase')=='showcase':
  for i,a in enumerate(s['actions']):derive(None,{'id':s['id'],'sceneId':s['id'],'type':'SHOWCASE'},a,i,s['start'])
# First representative of each fastener/contact type per step; repeated members subset.
cues=[];seen=collections.Counter();last=-10
for c in sorted(candidates,key=lambda x:x['globalTimestamp']):
 key=(c['step'],c['sceneId'],c['semanticEvent']);limit=1
 if c['semanticEvent']=='PART_SEAT':limit=2 if c['step']==1 else 1
 if c['semanticEvent'] in ['LEG_ATTACH','PISTON_ATTACH','BEARING_SEAT']:limit=2
 if seen[key]>=limit or (c['globalTimestamp']-last<.32 and c['semanticEvent'] not in ['BED_CLOSE','BED_OPEN','LEG_MOVEMENT','MECHANISM_MOVEMENT']):
  skipped.append({**c,'omissionReason':'Semantic compression: repeated/simultaneous connection or close repetition intentionally silent.'});continue
 if seen[key]:c['gainDb']-=3
 cues.append(c);seen[key]+=1;last=c['globalTimestamp']
# Calm completion confirmation only after all assembly actions have ended.
s=next(s for s in X['scenes'] if s['id']=='step-31');t=s['end'];cue(31,{'id':'step-31-complete','sceneId':s['id']},{'type':'assemblyComplete','target':'product-root','duration':0},0,t,'FINAL_SOFT_CONFIRMATION','soft-confirmation',t,.18,'All31 assembly steps complete; single subdued wood-like confirmation, no musical chime.',[t,t],contact=True,gain=-22);cues.append(candidates[-1]);cues.sort(key=lambda x:x['globalTimestamp'])
for c in cues:c['gainDb']+=6
for i,c in enumerate(cues):c['cueId']=f'C{i+1:03d}';c['onsetSample']=math.ceil(c['globalTimestamp']*SR-1e-8);c['renderedTimestamp']=c['onsetSample']/SR
counts=dict(collections.Counter(c['semanticEvent'] for c in cues));plan={'version':1,'musicDecision':'MUSIC_ASSET_REQUIRED','masterDuration':DURATION,'sampleRate':SR,'timelineOffset':5,'sourceTimeline':'semantic-timeline.json; DirectorPlanCompiler cumulative shot times + VideoEngine scene offsets','timingRule':'Continuous/turn cues stay within executable action phase; contact onset at the first30fps master frame showing the completed seating endpoint. Natural contact decay may follow the endpoint. No contact cues on staging/approach.','cueCount':len(cues),'countsBySemanticType':counts,'candidateCount':len(candidates),'omittedCount':len(skipped),'cues':cues};(P/'AudioCuePlan.json').write_text(json.dumps(plan,indent=2));(P/'omitted-cues.json').write_text(json.dumps(skipped,indent=2))
mix=np.zeros((round(DURATION*SR),2),dtype=np.float32)
for c in cues:
 with wave.open(str(P/c['soundAsset']),'rb') as w:a=np.frombuffer(w.readframes(w.getnframes()),dtype='<i2').astype(np.float64)/32768
 n=round(c['duration']*SR);a=np.interp(np.linspace(0,len(a)-1,n),np.arange(len(a)),a);t=np.arange(n)/SR;a*=np.minimum(1,t/c['fadeIn'])*np.minimum(1,np.maximum(0,(c['duration']-t)/c['fadeOut']))*10**(c['gainDb']/20)
 pan=-.12 if '--1' in (c['relatedPart'] or '') else .12 if '-1' in (c['relatedPart'] or '') else 0
 stereo=np.column_stack((a*np.sqrt((1-pan)/2),a*np.sqrt((1+pan)/2)));i=c['onsetSample'];assert i+n<=len(mix);mix[i:i+n]+=stereo
peak=float(np.max(np.abs(mix)));assert peak<.7;save(P/'WF311613-SFX-pass01.wav',mix)
windows=[]
for sec in range(math.ceil(DURATION)):
 a=mix[sec*SR:min((sec+1)*SR,len(mix))];windows.append({'second':sec,'peakDbfs':20*math.log10(max(1e-12,float(np.max(np.abs(a))))),'rmsDbfs':20*math.log10(max(1e-12,float(np.sqrt(np.mean(a*a))))),'nonzeroSamples':int(np.count_nonzero(a))})
(P/'waveform-summary.json').write_text(json.dumps({'samplePeakDbfs':20*math.log10(peak),'globalRmsDbfs':20*math.log10(float(np.sqrt(np.mean(mix*mix)))),'clippedSamples':int(np.count_nonzero(np.abs(mix)>=1)),'duration':len(mix)/SR,'windows':windows},indent=2));print('Cues:',len(cues),'Counts:',counts,'Peak:',20*math.log10(peak))
